allow changing statsd host, support python 3.6 and django 1.11
tom-dalton-fanduel/fdjangodog pull request #7
Opened 2017-08-01 22:59 UTC by AlJohri

2017-08-02 11:35 UTC, tom-dalton-fanduel commented on README.md
> +A simple Django middleware for submitting timings and exceptions to Datadog using statsd.
Maybe we should renamed "statsd" here to "DogStatsD" to be 100% clear https://docs.datadoghq.com/guides/dogstatsd/

2017-08-02 11:36 UTC, tom-dalton-fanduel commented on fdjangodog/middleware.py
> +if hasattr(settings, 'FDJANGODOG_STATSD_HOST'):
Could collapse this to a 1-liner with [getattr](https://docs.python.org/3.6/library/functions.html#getattr)

2017-08-02 11:39 UTC, tom-dalton-fanduel commented on fdjangodog/middleware.py
> +statsd = DogStatsd(host=statsd_host)
A *tiny* personal nitpick, I'd prefer to keep 2 lines before class definitions ref. [PEP8](https://www.python.org/dev/peps/pep-0008/#blank-lines)

2017-08-02 11:41 UTC, tom-dalton-fanduel requested changes
Couple of minor things but this looks pretty good to me - will be happy to merge when they're addressed!

2017-08-02 11:42 UTC, tom-dalton-fanduel commented on fdjangodog/middleware.py
> +statsd = DogStatsd(host=statsd_host)
(NB This comment applies to the class below this line in case it's not clear)

2017-08-02 11:43 UTC, tom-dalton-fanduel commented
One final thing, can you add a sentence in the Installation section of the README to document the new `FDJANGODOG_STATSD_HOST` setting?

2017-08-02 12:41 UTC, AlJohri commented
didn't realize how nice Github's web editing interface has gotten. made all the requested changes through the UI!

2017-08-02 13:28 UTC, tom-dalton-fanduel approved these changes

2017-08-02 13:28 UTC, tom-dalton-fanduel commented
Nice, thanks for this PR. I'll get it merged and deployed as a new verison in the (very) near future

2017-08-03 08:53 UTC, merged

2017-08-03 09:08 UTC, tom-dalton-fanduel commented
This is now merged and I've released fdjangodog 0.4.0.

Thanks a lot of the contribution!